user = input("введите название фильма: ")
user1 = input("введите название кинотеатра ")
user2 = input("введите время вашего фильма ")
Name = str (user)
teatre = str (user1)
time = str (user2)
ticket = (Name) + " в " + (teatre) + " на "+ (time)
print ("ваш билет на" , ticket, "забронирован")